version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    restart: always
    networks:
      - inception

###########

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html
    restart: always
    networks:
      - inception

###########

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    networks:
      - inception

###########

volumes:
  db_volume:
    # volumes are created on Docker host machine
    driver: local
    driver_opts:
      # no special partition in the host machine
      type: none
      # where in the host machine
      device: /home/${USER}/data/mariadb
      # bind mount, because is a special path outside volume docker area, can access from host machine
      o: bind
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

###########

networks:
  inception:
    name: inception-network
    driver: bridge
